version: '3.7'
services:
  db:
    image: postgres:14.3-alpine3.16
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=olegqa31
      - POSTGRES_PASSWORD=asTpo55nd